name: CI
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: npm
      - uses: google/wireit@setup-github-actions-caching/v2
      - run: npm ci
      - name: Validate
        run: npm run validate
      - uses: codecov/codecov-action@v7
        with:
          files: ./dist/coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
